spring:
  application:
    name: footbank

gateway:
  url: https://api.pagbrasilpay.com

resilience4j:
  circuitbreaker:
    instances:
      pagBrasilPay:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
